version: '3'
services:
  # Postgres image
  bucica_back_postgres:
    container_name: bucica_back_postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_bubica_back:/var/lib/postgresql/data

  # Node image
  bucica_back_app:
    container_name: bucica_back_app
    build: .
    env_file: .env.prod
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - bucica_back_postgres
      - bucica_back_nginx
    restart: always
    command: bash -c "npm run prod:start"

  # Nginx image
  bucica_back_nginx:
    container_name: bucica_back_nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  db_bubica_back:
