name: Deploy Hostinger
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalando Depedências
        run: npm i

      - name: Rodando Build
        run: npm run prod:build

  deploy:
    runs-on: self-hosted
    needs: build
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Criando .env.prod
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_DATABASE_URL: "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:5432/${{ secrets.POSTGRES_DB }}"
          envkey_PORT: ${{ secrets.PORT }}
          file_name: .env.prod
          fail_on_empty: true

      - name: Subir Container
        run: docker-compose -f docker-compose.prod.yml --env-file .env.prod down --rmi local && docker-compose -f docker-compose.prod.yml --env-file .env.prod up -d --build
